// Unit tests for vm/bignum.cpp, cross-checked against reference results
// generated by Python (vm/tests/gen_bignum_vectors.py) and against
// __int128 arithmetic for values that fit.
#include "test_vm.hpp"
#include "bignum_vectors.hpp"

using namespace factor;
using namespace factor::tests;

namespace {

typedef __int128_t int128;
typedef __uint128_t uint128;

const cell digit_bits = BIGNUM_DIGIT_LENGTH;
const cell digit_mask = BIGNUM_DIGIT_MASK;

// A VM with a large nursery and the bignum 0 / 1 / -1 singletons installed:
// bignum_trim, division and the small-constant fast paths hand those back
// through special_objects, exactly as a booted VM does.
struct bignum_vm {
  test_vm t;
  cell floor;

  bignum_vm() : t(8 * 1024 * 1024, 256 * 1024, 256 * 1024) {
    factor_vm& vm = t.vm;
    bignum* zero = vm.allot_bignum(0, 0);
    bignum* one = vm.allot_bignum(1, 0);
    BIGNUM_REF(one, 0) = 1;
    bignum* neg_one = vm.allot_bignum(1, 1);
    BIGNUM_REF(neg_one, 0) = 1;
    vm.special_objects[OBJ_BIGNUM_ZERO] = tag<bignum>(zero);
    vm.special_objects[OBJ_BIGNUM_POS_ONE] = tag<bignum>(one);
    vm.special_objects[OBJ_BIGNUM_NEG_ONE] = tag<bignum>(neg_one);
    floor = vm.nursery.here;
  }

  factor_vm& vm() { return t.vm; }

  // Recycle everything allocated after the singletons.
  void reset() { t.vm.nursery.here = floor; }

  static int hex_value(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    throw std::runtime_error(std::string("bad hex digit: ") + c);
  }

  // Build a bignum from a Python-style hex string ("-1f", "0").
  bignum* from_hex(const char* text) {
    std::string s(text);
    bool negative = !s.empty() && s[0] == '-';
    if (negative) s.erase(0, 1);
    std::vector<cell> digits;
    uint128 acc = 0;
    int bits = 0;
    for (size_t i = s.size(); i-- > 0;) {
      acc |= (uint128)hex_value(s[i]) << bits;
      bits += 4;
      if (bits >= (int)digit_bits) {
        digits.push_back((cell)(acc & digit_mask));
        acc >>= digit_bits;
        bits -= (int)digit_bits;
      }
    }
    if (bits > 0) digits.push_back((cell)(acc & digit_mask));
    while (!digits.empty() && digits.back() == 0) digits.pop_back();
    bignum* result = t.vm.allot_bignum((bignum_length_type)digits.size(),
                                       negative && !digits.empty());
    for (size_t i = 0; i < digits.size(); i++) BIGNUM_REF(result, i) = digits[i];
    return result;
  }

  bignum* from_int128(int128 v) {
    bool negative = v < 0;
    uint128 mag = negative ? (uint128)0 - (uint128)v : (uint128)v;
    std::vector<cell> digits;
    while (mag) {
      digits.push_back((cell)(mag & digit_mask));
      mag >>= digit_bits;
    }
    bignum* result = t.vm.allot_bignum((bignum_length_type)digits.size(), negative);
    for (size_t i = 0; i < digits.size(); i++) BIGNUM_REF(result, i) = digits[i];
    return result;
  }
};

std::string to_hex(bignum* bn) {
  bignum_length_type length = BIGNUM_LENGTH(bn);
  if (length == 0) return "0";
  // Stream the digits into nibbles, least significant first.
  std::string out;
  uint128 acc = 0;
  int bits = 0;
  for (bignum_length_type i = 0; i < length; i++) {
    acc |= (uint128)(BIGNUM_REF(bn, i) & digit_mask) << bits;
    bits += (int)digit_bits;
    while (bits >= 4) {
      out.push_back("0123456789abcdef"[acc & 0xf]);
      acc >>= 4;
      bits -= 4;
    }
  }
  while (bits > 0) {
    out.push_back("0123456789abcdef"[acc & 0xf]);
    acc >>= 4;
    bits -= 4;
  }
  while (out.size() > 1 && out.back() == '0') out.pop_back();
  if (BIGNUM_NEGATIVE_P(bn)) out.push_back('-');
  std::reverse(out.begin(), out.end());
  return out;
}

int128 to_int128(bignum* bn) {
  bignum_length_type length = BIGNUM_LENGTH(bn);
  if (length > 3) throw std::runtime_error("bignum does not fit in 128 bits");
  uint128 mag = 0;
  for (bignum_length_type i = length; i-- > 0;)
    mag = (mag << digit_bits) | (BIGNUM_REF(bn, i) & digit_mask);
  return BIGNUM_NEGATIVE_P(bn) ? -(int128)mag : (int128)mag;
}

std::string int128_to_hex(int128 v) {
  if (v == 0) return "0";
  bool negative = v < 0;
  uint128 mag = negative ? (uint128)0 - (uint128)v : (uint128)v;
  std::string out;
  while (mag) {
    out.push_back("0123456789abcdef"[mag & 0xf]);
    mag >>= 4;
  }
  if (negative) out.push_back('-');
  std::reverse(out.begin(), out.end());
  return out;
}

bool is_negative_hex(const char* s) { return s[0] == '-'; }

// Deterministic pseudo-random 128-bit values of varied width and shape.
struct rng {
  uint64_t state;
  explicit rng(uint64_t seed) : state(seed) {}
  uint64_t next() {
    state ^= state << 13;
    state ^= state >> 7;
    state ^= state << 17;
    return state;
  }
  int128 value(int max_bits) {
    int bits = (int)(next() % (max_bits + 1));
    uint128 mag = ((uint128)next() << 64) | next();
    if (bits < 128) mag &= (((uint128)1 << bits) - 1);
    switch (next() % 6) {
      case 0: mag = bits ? (((uint128)1 << bits) - 1) : 0; break;   // all ones
      case 1: mag = bits ? ((uint128)1 << (bits - 1)) : 0; break;   // one bit
      default: break;
    }
    int128 v = (int128)mag;
    return (next() & 1) ? -v : v;
  }
};

} // namespace

// std::ostream has no operator<< for __int128; the harness prints
// mismatches through show(), so give it one.
namespace factor { namespace tests {
inline std::string show(__int128_t v) { return int128_to_hex(v); }
} }

#define CHECK_HEX(expected, bn) CHECK_EQ(std::string(expected), to_hex(bn))
#define CHECK_I128(expected, actual) \
  CHECK_EQ(int128_to_hex(expected), int128_to_hex(actual))

// --- conversions ---

FACTOR_TEST(bignum_fixnum_and_cell_round_trips) {
  bignum_vm b;
  factor_vm& vm = b.vm();

  const fixnum fixnums[] = {0, 1, -1, 2, -2, fixnum_max, fixnum_min,
                            fixnum_max + 1, fixnum_min - 1,
                            (fixnum)1 << 61, -((fixnum)1 << 61),
                            INT64_MAX, INT64_MIN + 1};
  for (fixnum n : fixnums) {
    bignum* bn = vm.fixnum_to_bignum(n);
    CHECK_EQ(n < 0, BIGNUM_NEGATIVE_P(bn) != 0);
    CHECK_EQ(n, bignum_to_fixnum(bn));
    CHECK_EQ((int64_t)n, bignum_to_int64(bn));
    CHECK_HEX(int128_to_hex(n), bn);
    CHECK_HEX(int128_to_hex(n), vm.int64_to_bignum(n));
  }
  CHECK_EQ((bignum_length_type)0, BIGNUM_LENGTH(vm.fixnum_to_bignum(0)));
  CHECK_EQ(vm.special_objects[OBJ_BIGNUM_ZERO], tag<bignum>(vm.fixnum_to_bignum(0)));
  CHECK_EQ(vm.special_objects[OBJ_BIGNUM_POS_ONE], tag<bignum>(vm.fixnum_to_bignum(1)));
  CHECK_EQ(vm.special_objects[OBJ_BIGNUM_NEG_ONE], tag<bignum>(vm.fixnum_to_bignum(-1)));

  const cell cells[] = {0, 1, (cell)fixnum_max, (cell)fixnum_max + 1,
                        (cell)1 << 62, (cell)1 << 63, UINT64_MAX};
  for (cell n : cells) {
    bignum* bn = vm.cell_to_bignum(n);
    CHECK(!BIGNUM_NEGATIVE_P(bn));
    CHECK_EQ(n, bignum_to_cell(bn));
    CHECK_EQ((uint64_t)n, bignum_to_uint64(bn));
    CHECK_HEX(int128_to_hex((int128)(uint128)n), bn);
    CHECK_HEX(int128_to_hex((int128)(uint128)n), vm.uint64_to_bignum(n));
  }
  // Two digits are needed above 2^62.
  CHECK_EQ((bignum_length_type)2, BIGNUM_LENGTH(vm.cell_to_bignum((cell)1 << 62)));
  CHECK_EQ((bignum_length_type)1, BIGNUM_LENGTH(vm.cell_to_bignum(((cell)1 << 62) - 1)));
}

FACTOR_TEST(bignum_int64_min_round_trip) {
  // BUG (fixed by factor/factor#3218, not on this branch): the signed
  // conversion macro negates n as a signed value, undefined for INT64_MIN.
  bignum_vm b;
  bignum* bn = b.vm().fixnum_to_bignum(INT64_MIN);
  if (to_hex(bn) != "-8000000000000000")
    SKIP_TEST("factor/factor#3218: fixnum_to_bignum(INT64_MIN) gave " + to_hex(bn));
  CHECK_EQ(INT64_MIN, bignum_to_int64(bn));
  CHECK_HEX("-8000000000000000", b.vm().int64_to_bignum(INT64_MIN));
}

FACTOR_TEST(bignum_maybe_to_fixnum_normalizes_at_the_boundaries) {
  bignum_vm b;
  factor_vm& vm = b.vm();
  CHECK_EQ(tag_fixnum(fixnum_max), bignum_maybe_to_fixnum(vm.fixnum_to_bignum(fixnum_max)));
  CHECK_EQ(tag_fixnum(fixnum_min), bignum_maybe_to_fixnum(vm.fixnum_to_bignum(fixnum_min)));
  CHECK_EQ(tag_fixnum(0), bignum_maybe_to_fixnum(vm.fixnum_to_bignum(0)));
  cell above = bignum_maybe_to_fixnum(vm.fixnum_to_bignum(fixnum_max + 1));
  CHECK_EQ((cell)BIGNUM_TYPE, TAG(above));
  cell below = bignum_maybe_to_fixnum(vm.fixnum_to_bignum(fixnum_min - 1));
  CHECK_EQ((cell)BIGNUM_TYPE, TAG(below));
  CHECK_EQ(fixnum_max, vm.bignum_to_fixnum_strict(vm.fixnum_to_bignum(fixnum_max)));
  CHECK_EQ(fixnum_min, vm.bignum_to_fixnum_strict(vm.fixnum_to_bignum(fixnum_min)));
}

FACTOR_TEST(bignum_hex_helpers_round_trip) {
  bignum_vm b;
  const char* samples[] = {"0", "1", "-1", "3fffffffffffffff", "4000000000000000",
                           "-4000000000000000", "ffffffffffffffffffffffffffffffff",
                           "-123456789abcdef0123456789abcdef0123456789abcdef"};
  for (const char* s : samples) CHECK_HEX(s, b.from_hex(s));
  CHECK_EQ((bignum_length_type)1, BIGNUM_LENGTH(b.from_hex("3fffffffffffffff")));
  CHECK_EQ((bignum_length_type)2, BIGNUM_LENGTH(b.from_hex("4000000000000000")));
  CHECK_EQ((bignum_length_type)3, BIGNUM_LENGTH(b.from_hex("ffffffffffffffffffffffffffffffff")));
  int128 v = ((int128)0x123456789abcdefLL << 64) | 0xfedcba9876543210ULL;
  CHECK_I128(v, to_int128(b.from_int128(v)));
  CHECK_I128(-v, to_int128(b.from_int128(-v)));
  CHECK_HEX(int128_to_hex(v), b.from_int128(v));
}

// --- reference vectors ---

FACTOR_TEST(bignum_compare_and_equal_vectors) {
  bignum_vm b;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    b.reset();
    bignum* x = b.from_hex(v.a);
    bignum* y = b.from_hex(v.b);
    int expected = strcmp(v.difference, "0") == 0 ? 0
                   : is_negative_hex(v.difference) ? -1 : 1;
    CHECK_EQ(expected, (int)b.vm().bignum_compare(x, y));
    CHECK_EQ(-expected, (int)b.vm().bignum_compare(y, x));
    CHECK_EQ(expected == 0, b.vm().bignum_equal_p(x, y) != 0);
    CHECK(b.vm().bignum_equal_p(x, x));
  }
}

FACTOR_TEST(bignum_add_subtract_multiply_vectors) {
  bignum_vm b;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    b.reset();
    bignum* x = b.from_hex(v.a);
    bignum* y = b.from_hex(v.b);
    CHECK_HEX(v.sum, b.vm().bignum_add(x, y));
    CHECK_HEX(v.sum, b.vm().bignum_add(y, x));
    CHECK_HEX(v.difference, b.vm().bignum_subtract(x, y));
    CHECK_HEX(v.product, b.vm().bignum_multiply(x, y));
    CHECK_HEX(v.product, b.vm().bignum_multiply(y, x));
    // Squaring must agree with the general multiply.
    CHECK_HEX(to_hex(b.vm().bignum_multiply(x, x)), b.vm().bignum_square(x));
    // (x + y) - y == x
    CHECK_HEX(v.a, b.vm().bignum_subtract(b.vm().bignum_add(x, y), y));
  }
}

FACTOR_TEST(bignum_division_vectors) {
  bignum_vm b;
  int divisions = 0;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    if (v.quotient[0] == '\0') continue;
    divisions++;
    b.reset();
    bignum* x = b.from_hex(v.a);
    bignum* y = b.from_hex(v.b);
    CHECK_HEX(v.quotient, b.vm().bignum_quotient(x, y));
    CHECK_HEX(v.remainder, b.vm().bignum_remainder(x, y));
    bignum* q = NULL;
    bignum* r = NULL;
    b.vm().bignum_divide(x, y, &q, &r);
    CHECK_HEX(v.quotient, q);
    CHECK_HEX(v.remainder, r);
    // q * y + r == x
    CHECK_HEX(v.a, b.vm().bignum_add(b.vm().bignum_multiply(q, y), r));
  }
  CHECK(divisions > 250);
}

FACTOR_TEST(bignum_gcd_vectors) {
  bignum_vm b;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    b.reset();
    bignum* x = b.from_hex(v.a);
    bignum* y = b.from_hex(v.b);
    CHECK_HEX(v.gcd, b.vm().bignum_gcd(x, y));
    CHECK_HEX(v.gcd, b.vm().bignum_gcd(y, x));
  }
}

FACTOR_TEST(bignum_and_or_not_vectors) {
  bignum_vm b;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    b.reset();
    bignum* x = b.from_hex(v.a);
    bignum* y = b.from_hex(v.b);
    CHECK_HEX(v.bit_and, b.vm().bignum_bitwise_and(x, y));
    CHECK_HEX(v.bit_and, b.vm().bignum_bitwise_and(y, x));
    CHECK_HEX(v.bit_or, b.vm().bignum_bitwise_ior(x, y));
    CHECK_HEX(v.bit_or, b.vm().bignum_bitwise_ior(y, x));
    CHECK_HEX(v.a_not, b.vm().bignum_bitwise_not(x));
    CHECK_HEX(v.a, b.vm().bignum_bitwise_not(b.vm().bignum_bitwise_not(x)));
  }
}

FACTOR_TEST(bignum_xor_vectors) {
  // BUG (fixed by factor/factor#3217, not on this branch): xor of a positive
  // and a negative operand sizes its result one digit short when the
  // magnitude needs a new top digit, e.g. (2^124 - 1) xor -1 = -2^124 comes
  // out as 0. Mixed-sign mismatches are collected and reported as a skip so
  // the same-sign cases still count.
  bignum_vm b;
  int mixed_sign_mismatches = 0;
  std::string first_mismatch;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    b.reset();
    bignum* x = b.from_hex(v.a);
    bignum* y = b.from_hex(v.b);
    std::string got_xy = to_hex(b.vm().bignum_bitwise_xor(x, y));
    std::string got_yx = to_hex(b.vm().bignum_bitwise_xor(y, x));
    bool mixed = is_negative_hex(v.a) != is_negative_hex(v.b);
    if (mixed && (got_xy != v.bit_xor || got_yx != v.bit_xor)) {
      mixed_sign_mismatches++;
      if (first_mismatch.empty())
        first_mismatch = std::string(v.a) + " xor " + v.b + " expected " +
                         v.bit_xor + " got " + got_xy;
      continue;
    }
    CHECK_EQ(std::string(v.bit_xor), got_xy);
    CHECK_EQ(std::string(v.bit_xor), got_yx);
  }
  if (mixed_sign_mismatches)
    SKIP_TEST("factor/factor#3217: " + show(mixed_sign_mismatches) +
              " mixed-sign xor mismatches, e.g. " + first_mismatch);
}

FACTOR_TEST(bignum_xor_mixed_sign_needs_extra_digit) {
  // BUG (fixed by factor/factor#3217, not on this branch): see
  // bignum_xor_vectors. Each case needs one more digit than either operand.
  bignum_vm b;
  struct { const char* a; const char* b; const char* expected; } cases[] = {
      {"3fffffffffffffff", "-1", "-4000000000000000"},                          // (2^62 - 1) xor -1
      {"fffffffffffffffffffffffffffffff", "-1",
       "-10000000000000000000000000000000"},                                      // (2^124 - 1) xor -1
      {"3fffffffffffffffffffffffffffffffffffffffffffffff", "-1",
       "-4000000000000000000000000000000000000000000000000"},                    // (2^186 - 1) xor -1
      {"fffffffffffffffffffffffffffffff", "-2",
       "-fffffffffffffffffffffffffffffff"},                                       // (2^124 - 1) xor -2
  };
  bool failed = false;
  std::string detail;
  for (auto& c : cases) {
    b.reset();
    bignum* x = b.from_hex(c.a);
    bignum* y = b.from_hex(c.b);
    std::string got_xy = to_hex(b.vm().bignum_bitwise_xor(x, y));
    std::string got_yx = to_hex(b.vm().bignum_bitwise_xor(y, x));
    if (got_xy != c.expected || got_yx != c.expected) {
      failed = true;
      if (detail.empty())
        detail = std::string(c.a) + " xor " + c.b + " expected " + c.expected +
                 " got " + got_xy + " / " + got_yx;
    }
  }
  if (failed) SKIP_TEST("factor/factor#3217: " + detail);
}

FACTOR_TEST(bignum_shift_vectors) {
  bignum_vm b;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    b.reset();
    bignum* x = b.from_hex(v.a);
    CHECK_HEX(v.shifted, b.vm().bignum_arithmetic_shift(x, v.shift));
    CHECK_HEX(v.a, b.vm().bignum_arithmetic_shift(x, 0));
    // Shifting left then right by the same amount is the identity.
    CHECK_HEX(v.a, b.vm().bignum_arithmetic_shift(
                       b.vm().bignum_arithmetic_shift(x, 100), -100));
  }
}

FACTOR_TEST(bignum_shift_across_digit_boundaries) {
  bignum_vm b;
  factor_vm& vm = b.vm();
  bignum* one = b.from_hex("1");
  CHECK_HEX("4000000000000000", vm.bignum_arithmetic_shift(one, 62));
  CHECK_HEX("10000000000000000000000000000000", vm.bignum_arithmetic_shift(one, 124));
  CHECK_EQ((bignum_length_type)2, BIGNUM_LENGTH(vm.bignum_arithmetic_shift(one, 62)));
  CHECK_EQ((bignum_length_type)3, BIGNUM_LENGTH(vm.bignum_arithmetic_shift(one, 124)));
  bignum* big = vm.bignum_arithmetic_shift(one, 124);
  CHECK_HEX("1", vm.bignum_arithmetic_shift(big, -124));
  CHECK_HEX("0", vm.bignum_arithmetic_shift(big, -125));
  CHECK_HEX("0", vm.bignum_arithmetic_shift(big, -1000));
  // Negative values shift right with floor semantics.
  CHECK_HEX("-1", vm.bignum_arithmetic_shift(b.from_hex("-1"), -1));
  CHECK_HEX("-1", vm.bignum_arithmetic_shift(b.from_hex("-1"), -200));
  CHECK_HEX("-1", vm.bignum_arithmetic_shift(b.from_hex("-4000000000000000"), -62));
  CHECK_HEX("-2", vm.bignum_arithmetic_shift(b.from_hex("-4000000000000001"), -62));
  CHECK_HEX("-3", vm.bignum_arithmetic_shift(b.from_hex("-4000000000000001"), -61));
  CHECK_HEX("-2000000000000000", vm.bignum_arithmetic_shift(b.from_hex("-3fffffffffffffff"), -1));
  CHECK_HEX("0", vm.bignum_arithmetic_shift(vm.fixnum_to_bignum(0), 500));
}

FACTOR_TEST(bignum_integer_length_vectors) {
  bignum_vm b;
  for (int i = 0; i < bignum_vector_count; i++) {
    const bignum_vector& v = bignum_vectors[i];
    if (strcmp(v.a, "0") == 0) continue;
    b.reset();
    // bignum_integer_length is floor(log2 |x|), i.e. bit length - 1; this is
    // what primitive_bignum_log2 relies on.
    CHECK_HEX(int128_to_hex(v.a_bit_length - 1),
              b.vm().bignum_integer_length(b.from_hex(v.a)));
  }
  CHECK_HEX("3d", b.vm().bignum_integer_length(b.from_hex("3fffffffffffffff")));
  CHECK_HEX("3e", b.vm().bignum_integer_length(b.from_hex("4000000000000000")));
  CHECK_HEX("3e", b.vm().bignum_integer_length(b.from_hex("-4000000000000000")));
}

// --- __int128 loops ---

FACTOR_TEST(bignum_arithmetic_matches_int128) {
  bignum_vm b;
  rng r(0x5eed0001);
  for (int i = 0; i < 1500; i++) {
    b.reset();
    int128 x = r.value(120), y = r.value(120);
    bignum* bx = b.from_int128(x);
    bignum* by = b.from_int128(y);
    CHECK_I128(x + y, to_int128(b.vm().bignum_add(bx, by)));
    CHECK_I128(x - y, to_int128(b.vm().bignum_subtract(bx, by)));
    int128 sx = r.value(60), sy = r.value(60);
    CHECK_I128(sx * sy, to_int128(b.vm().bignum_multiply(b.from_int128(sx), b.from_int128(sy))));
    CHECK_I128(sx * sx, to_int128(b.vm().bignum_square(b.from_int128(sx))));
    if (y != 0) {
      CHECK_I128(x / y, to_int128(b.vm().bignum_quotient(bx, by)));
      CHECK_I128(x % y, to_int128(b.vm().bignum_remainder(bx, by)));
    }
    int expected_cmp = x < y ? -1 : x > y ? 1 : 0;
    CHECK_EQ(expected_cmp, (int)b.vm().bignum_compare(bx, by));
    CHECK_EQ(x == y, b.vm().bignum_equal_p(bx, by) != 0);
    CHECK_I128(x, to_int128(bx));
  }
}

FACTOR_TEST(bignum_bitwise_matches_int128) {
  bignum_vm b;
  rng r(0x5eed0002);
  int mixed_sign_xor_mismatches = 0;
  for (int i = 0; i < 1500; i++) {
    b.reset();
    int128 x = r.value(120), y = r.value(120);
    bignum* bx = b.from_int128(x);
    bignum* by = b.from_int128(y);
    CHECK_I128(x & y, to_int128(b.vm().bignum_bitwise_and(bx, by)));
    CHECK_I128(x | y, to_int128(b.vm().bignum_bitwise_ior(bx, by)));
    CHECK_I128(~x, to_int128(b.vm().bignum_bitwise_not(bx)));
    int128 got_xor = to_int128(b.vm().bignum_bitwise_xor(bx, by));
    if (got_xor != (x ^ y)) {
      // See bignum_xor_vectors: factor/factor#3217.
      if ((x < 0) != (y < 0)) mixed_sign_xor_mismatches++;
      else CHECK_I128(x ^ y, got_xor);
    }
    int k = (int)(r.next() % 126);
    CHECK_EQ((int)((x >> k) & 1), b.vm().bignum_logbitp(k, bx));
    int s = (int)(r.next() % 70);
    CHECK_I128(x >> s, to_int128(b.vm().bignum_arithmetic_shift(bx, -s)));
    if (x != 0) {
      // Left shifts that stay inside 126 bits.
      int width = 0;
      uint128 mag = x < 0 ? (uint128)0 - (uint128)x : (uint128)x;
      while (width < 128 && (mag >> width)) width++;
      int l = (int)(r.next() % (126 - width + 1));
      CHECK_I128(x * ((int128)1 << l), to_int128(b.vm().bignum_arithmetic_shift(bx, l)));
    }
  }
  if (mixed_sign_xor_mismatches)
    SKIP_TEST("factor/factor#3217: " + show(mixed_sign_xor_mismatches) +
              " mixed-sign xor mismatches");
}

FACTOR_TEST(bignum_logbitp_and_sign_extension) {
  bignum_vm b;
  factor_vm& vm = b.vm();
  bignum* x = b.from_hex("4000000000000000"); // 2^62
  CHECK_EQ(0, vm.bignum_logbitp(0, x));
  CHECK_EQ(0, vm.bignum_logbitp(61, x));
  CHECK_EQ(1, vm.bignum_logbitp(62, x));
  CHECK_EQ(0, vm.bignum_logbitp(63, x));
  CHECK_EQ(0, vm.bignum_logbitp(1000, x));
  bignum* neg = b.from_hex("-4000000000000000"); // -2^62: ...111 1000...0
  CHECK_EQ(0, vm.bignum_logbitp(61, neg));
  CHECK_EQ(1, vm.bignum_logbitp(62, neg));
  CHECK_EQ(1, vm.bignum_logbitp(63, neg));
  CHECK_EQ(1, vm.bignum_logbitp(1000, neg));
  bignum* minus_one = b.from_hex("-1");
  CHECK_EQ(1, vm.bignum_logbitp(0, minus_one));
  CHECK_EQ(1, vm.bignum_logbitp(500, minus_one));
}

// --- doubles ---

FACTOR_TEST(bignum_double_to_bignum) {
  bignum_vm b;
  factor_vm& vm = b.vm();
  CHECK_HEX("0", vm.double_to_bignum(0.0));
  CHECK_HEX("0", vm.double_to_bignum(0.5));
  CHECK_HEX("0", vm.double_to_bignum(-0.999));
  CHECK_HEX("0", vm.double_to_bignum(std::numeric_limits<double>::infinity()));
  CHECK_HEX("0", vm.double_to_bignum(-std::numeric_limits<double>::infinity()));
  CHECK_HEX("0", vm.double_to_bignum(std::numeric_limits<double>::quiet_NaN()));
  CHECK_EQ(vm.special_objects[OBJ_BIGNUM_POS_ONE], tag<bignum>(vm.double_to_bignum(1.0)));
  CHECK_EQ(vm.special_objects[OBJ_BIGNUM_NEG_ONE], tag<bignum>(vm.double_to_bignum(-1.0)));
  CHECK_HEX("1", vm.double_to_bignum(1.75));
  CHECK_HEX("2", vm.double_to_bignum(2.0));
  CHECK_HEX("3", vm.double_to_bignum(3.999));
  CHECK_HEX("-3", vm.double_to_bignum(-3.999));
  for (int e = 1; e <= 300; e += 7) {
    b.reset();
    // Exact powers of two, and 3 * 2^(e-1) which has two significant bits.
    const char* nibble = "1248";
    std::string expected = std::string(1, nibble[e % 4]) + std::string(e / 4, '0');
    CHECK_HEX(expected, vm.double_to_bignum(ldexp(1.0, e)));
    CHECK_HEX("-" + expected, vm.double_to_bignum(-ldexp(1.0, e)));
    if (e >= 2) {
      bignum* want = vm.bignum_arithmetic_shift(b.from_hex("3"), e - 1);
      CHECK_HEX(to_hex(want), vm.double_to_bignum(ldexp(3.0, e - 1)));
    }
  }
  // A 53-bit significand spread over several digits, then truncation of
  // fractional bits below the digit boundary.
  double v = ldexp((double)0x1fffffffffffffLL, 100); // (2^53 - 1) * 2^100
  bignum* expected = vm.bignum_arithmetic_shift(b.from_hex("1fffffffffffff"), 100);
  CHECK_HEX(to_hex(expected), vm.double_to_bignum(v));
  CHECK_HEX("-" + to_hex(expected), vm.double_to_bignum(-v));
  CHECK_HEX("1fffffffffffff", vm.double_to_bignum((double)0x1fffffffffffffLL));
  CHECK_HEX("fffffffffffff8", vm.double_to_bignum(ldexp((double)0x1fffffffffffffLL, 3)));
}

FACTOR_TEST(bignum_new_sign_and_trim) {
  bignum_vm b;
  factor_vm& vm = b.vm();
  bignum* x = b.from_hex("123456789abcdef0123");
  CHECK_HEX("-123456789abcdef0123", vm.bignum_new_sign(x, 1));
  CHECK_HEX("123456789abcdef0123", vm.bignum_new_sign(x, 0));
  CHECK_EQ(x, vm.bignum_maybe_new_sign(x, 0));
  CHECK_HEX("-123456789abcdef0123", vm.bignum_maybe_new_sign(x, 1));
  // A bignum with leading zero digits is trimmed, and a trimmed zero loses
  // its sign.
  bignum* padded = vm.allot_bignum_zeroed(4, 1);
  BIGNUM_REF(padded, 0) = 5;
  bignum* trimmed = vm.bignum_trim(padded);
  CHECK_EQ((bignum_length_type)1, BIGNUM_LENGTH(trimmed));
  CHECK_HEX("-5", trimmed);
  bignum* zero_padded = vm.allot_bignum_zeroed(3, 1);
  bignum* zero = vm.bignum_trim(zero_padded);
  CHECK_EQ((bignum_length_type)0, BIGNUM_LENGTH(zero));
  CHECK(!BIGNUM_NEGATIVE_P(zero));
  CHECK_HEX("0", zero);
}
