#!/usr/bin/env python3
"""Generate vm/tests/bignum_vectors.hpp: reference results for the VM's
bignum arithmetic, computed with Python's integers.

Python's semantics match Factor's for every operation here: floor shifts,
two's complement bitwise operations, truncating quotient/remainder (we
apply the signs by hand), and a non-negative gcd.

Run from the repository root:  python3 vm/tests/gen_bignum_vectors.py
"""
import random

DIGIT_BITS = 62
random.seed(0x5EED_B16)


def shaped(digits):
    """A random non-negative integer of about `digits` 62-bit digits, with a
    bias toward the shapes that trip carry and normalization logic."""
    if digits == 0:
        return 0
    bits = digits * DIGIT_BITS
    kind = random.randrange(8)
    if kind == 0:
        return (1 << bits) - 1                # all ones
    if kind == 1:
        return 1 << (bits - 1)                # single top bit
    if kind == 2:
        return 1 << random.randrange(bits)    # single bit anywhere
    if kind == 3:
        return random.getrandbits(bits) | (1 << (bits - 1))  # full width
    if kind == 4:
        return (1 << bits) - random.randrange(1, 1 << 16)    # near the top
    if kind == 5:
        top = random.getrandbits(4) or 1                      # short top digit
        return (top << (bits - DIGIT_BITS)) | random.getrandbits(bits - DIGIT_BITS)
    return random.getrandbits(bits) or 1


def signed(digits):
    v = shaped(digits)
    return -v if v and random.random() < 0.5 else v


def hx(v):
    return ("-" if v < 0 else "") + format(abs(v), "x")


def trunc_divmod(a, b):
    q = abs(a) // abs(b)
    r = abs(a) - q * abs(b)
    if (a < 0) != (b < 0):
        q = -q
    if a < 0:
        r = -r
    return q, r


cases = []
# Every combination of small digit counts, then random larger ones.
for da in range(0, 4):
    for db in range(0, 4):
        for _ in range(4):
            cases.append((signed(da), signed(db)))
for _ in range(220):
    cases.append((signed(random.randrange(0, 7)), signed(random.randrange(0, 7))))
# Knuth q-hat correction shapes: numerator with all-ones digits, divisor with
# a top digit just above half the radix or of the form 1000...0001.
half = 1 << (DIGIT_BITS - 1)
for _ in range(24):
    n = (1 << (DIGIT_BITS * random.randrange(3, 6))) - random.randrange(1, 1 << 20)
    d_top = random.choice([half, half + 1, (1 << DIGIT_BITS) - 1, half | 1])
    d = (d_top << (DIGIT_BITS * random.randrange(1, 3))) | random.choice([0, 1, (1 << DIGIT_BITS) - 1])
    cases.append((random.choice([n, -n]), random.choice([d, -d])))
# The mixed-sign xor shape from factor/factor#3217.
for k in (1, 2, 3):
    cases.append(((1 << (DIGIT_BITS * k)) - 1, -1))
    cases.append((-1, (1 << (DIGIT_BITS * k)) - 1))
    cases.append(((1 << (DIGIT_BITS * k)) - 1, -2))

lines = []
lines.append("// Generated by vm/tests/gen_bignum_vectors.py; do not edit by hand.")
lines.append("// Each entry holds two operands and the reference results as hex strings")
lines.append("// (sign prefix, no leading zeros, \"0\" for zero).")
lines.append("#ifndef FACTOR_TESTS_BIGNUM_VECTORS_HPP")
lines.append("#define FACTOR_TESTS_BIGNUM_VECTORS_HPP")
lines.append("")
lines.append("namespace factor { namespace tests {")
lines.append("")
lines.append("struct bignum_vector {")
lines.append("  const char* a;")
lines.append("  const char* b;")
lines.append("  const char* sum;")
lines.append("  const char* difference;")
lines.append("  const char* product;")
lines.append("  const char* quotient;   // truncated toward zero; \"\" when b == 0")
lines.append("  const char* remainder;  // sign of a; \"\" when b == 0")
lines.append("  const char* gcd;")
lines.append("  const char* bit_and;")
lines.append("  const char* bit_or;")
lines.append("  const char* bit_xor;")
lines.append("  int shift;              // arithmetic shift amount applied to a")
lines.append("  const char* shifted;    // a << shift (floor semantics when negative)")
lines.append("  const char* a_not;      // ~a")
lines.append("  int a_bit_length;       // a.bit_length()")
lines.append("};")
lines.append("")
lines.append("static const bignum_vector bignum_vectors[] = {")
import math
for a, b in cases:
    if b:
        q, r = trunc_divmod(a, b)
        qs, rs = hx(q), hx(r)
    else:
        qs = rs = ""
    shift = random.choice([0, 1, 5, 61, 62, 63, 100, 124, 125, 200, -1, -5, -61, -62, -63, -100, -124, -125, -200])
    shifted = a << shift if shift >= 0 else a >> -shift
    lines.append('  {"%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s", "%s", %d, "%s", "%s", %d},' % (
        hx(a), hx(b), hx(a + b), hx(a - b), hx(a * b), qs, rs, hx(math.gcd(a, b)),
        hx(a & b), hx(a | b), hx(a ^ b), shift, hx(shifted), hx(~a), abs(a).bit_length()))
lines.append("};")
lines.append("")
lines.append("static const int bignum_vector_count = sizeof(bignum_vectors) / sizeof(bignum_vectors[0]);")
lines.append("")
lines.append("} }")
lines.append("")
lines.append("#endif")
with open("vm/tests/bignum_vectors.hpp", "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", len(cases), "cases")
